spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange?reWriteBatchedInserts=true
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
server:
  error:
    include-message: always