spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange?reWriteBatchedInserts=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
      # show_sql: true
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      topic: input-ticket

logging:
  level:
    org:
      springframework: DEBUG
server:
  error:
    include-message: always
exchange-portal:
  allowed-origins: ${EXCHANGE_PORTAL_ALLOWED_ORIGINS:http://localhost:4200} #comma separated list
  security:
    keycloak:
      url: ${KEYCLOAK_URL:http://localhost:8081}