services:
  db:
    image: exchange/db
    build:
      context: backend-external
      dockerfile: Dockerfile-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange
    healthcheck:
      test: [ "CMD-SHELL", "test $(psql -U postgres -d exchange -c 'SELECT count(id) FROM exchange.user' -t) -gt 0 || exit 1" ]
      interval: 10s
      retries: 20
  backend-external:
    image: exchange/image-external
    build:
      context: backend-external
      dockerfile: Dockerfile-backend-external
    ports:
      - 8080:8080