services:
  keycloak:
    image: exchange/keycloak
    build:
      context: keycloak
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - KC_HOSTNAME_URL=http://keycloak:8081
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
  db:
    image: exchange/db
    build:
      context: backend-internal
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exchange
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CREATE_TOPICS: "cash_transaction-topic:1:20,internal-ticket-topic:1:20,external-account-topic:1:20, internal-exchanges-topic:1:20, internal-account-topic:1:20, external-order-book-topic:1:20, external-account-list-topic:1:2, internal-account-list-topic:1:2"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend-internal:
    image: exchange/backend-internal
    build:
      context: backend-internal
      dockerfile: Dockerfile-backend-internal
    environment:
      DB_ADDRESS: db
      DB_PORT: 5432
      DB_NAME: exchange
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EXCHANGE_RATIO_STRATEGY: org.exchange.strategies.ratio.FirstTicketRatioStrategy
    ports:
      - "8070:8070"
    depends_on:
      - kafka
      - db

  backend-external:
    image: exchange/backend-external
    build:
      context: backend-external
      dockerfile: Dockerfile-backend-external
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - db
      - backend-internal
    environment:
      DB_ADDRESS: db
      DB_PORT: 5432
      DB_NAME: exchange
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  backend-admin:
    image: exchange/backend-admin
    build:
      context: backend-admin
      dockerfile: Dockerfile-backend-admin
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - db
      - backend-internal
    environment:
      DB_ADDRESS: db
      DB_PORT: 5432
      DB_NAME: exchange
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092