openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for Exchange System application.
  version: 1.0.0
components:
  schemas:
    Pair:
      type: string
      enum:
        - EUR_PLN
        - USD_PLN
        - CHF_PLN
        - GBP_PLN
        - EUR_USD
        - EUR_CHF
        - EUR_GBP
        - GBP_USD
        - USD_CHF
        - GBP_CHF
    Currency:
      type: string
      enum:
        - EUR
        - USD
        - GBP
        - CHF
        - PLN

    Direction:
      type: string
      enum:
        - SELL
        - BUY
    EventType:
      type: string
      enum:
        - DEPOSIT
        - WITHDRAW
        - EXCHANGE
        - CORRECTION
        - FEE
    Order:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - value
      properties:
        id:
          type: string
          format: uuid
        pair:
          $ref: '#/components/schemas/Pair'
        value:
          type: integer
          format: int64
        direction:
          $ref: '#/components/schemas/Direction'
        ratio:
          type: integer
          format: int64
        event:
          type: string
        ip:
          type: string
        user:
          type: string
        hash:
          type: integer
          format: int64
        journal:
          type: boolean
        checkedFinance:
          type: boolean
        marshalled:
          type: boolean
        haveData:
          type: boolean
    UserAccount:
      type: object
      required:
        - idUser
        - currency
      properties:
        id:
          type: string
          format: uuid
        idUser:
          type: string
          format: uuid
        currency:
          $ref: '#/components/schemas/Currency'
    UserTicket:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - value
        - epochUTC
        - idUser
      properties:
        id:
          type: integer
          format: int64
        value:
          type: integer
          format: int64
        ratio:
          type: integer
          format: int64
        idUser:
          type: string
          format: uuid
        idUserAccount:
          type: string
          format: uuid
        pair:
          $ref: '#/components/schemas/Pair'
        epochUTC:
          type: integer
          format: int64
        direction:
          $ref: '#/components/schemas/Direction'

    ErrorResponse:
      type: object
      properties:
        errorCode:
          type: string
          description: A code representing the type of error
        errorId:
          type: string
          format: uuid
          description: A unique identifier for the error instance
        message:
          type: string
          description: A descriptive message explaining the error
        timestampUTC:
          type: string
          format: datetime
          description: The timestamp when the error occurred, recorded in UTC timezone