openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for Exchange System application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /orders/book:
    get:
      summary: get all orders
      operationId: getOrderBook
      tags:
        - orders
      responses:
        '200':
          description: All Orders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: Order
components:
  schemas:

    CancelOrder:
      type: object
      required:
        - idOrder
        - idCancelOrder
        - pair
        - direction
      properties:
        idOrder:
          type: string
          format: uuid
        idCancelOrder:
          type: string
          format: uuid
        pair:
          type: Pair
        direction:
          type: Direction
    OrderTicket:
      type: object
      required:
        - id
        - valueAmount
        - idUser
        - idCurrency
        - ratio
        - ticketDateUTC
        - pair
        - direction
        - finishOrder
        - flagSaved
        - flagCancelled
      properties:
        id:
          type: integer
          format: int64
        idUser:
          type: integer
          format: int64
        pair:
          type: Pair
        direction:
          type: Direction
        ticketDateUTC:
          description: UTC timezone
          type: string
          format: date-time
        ratio:
          type: number
        valueAmount:
          type: number
        finishOrder:
          type: boolean
          default: false
        idCurrency:
          type: string
        flagSaved:
          type: boolean
          default: false
        flagCancelled:
          type: boolean
          default: false
    ExchangeTicket:
      allOf:
        - $ref: "#/components/schemas/OrderTicket"
        - type: object
          properties:
            idOrderReverse:
              type: integer
              format: int64
            exchangeDateUTC:
              description: UTC timezone
              type: string
              format: date-time
    ExchangeEvent:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - idUser
        - journal
        - checkedFinance
        - marshalled
        - haveData
      properties:
        id:
          type: integer
          format: int64
        action:
          type: string
        pair:
          type: Pair
        value:
          type: number
        direction:
          type: Direction
        ratio:
          type: number
        event:
          type: string
        ip:
          type: string
        idUser:
          type: integer
          format: int64
        hash:
          type: integer
          format: int64
        journal:
          type: boolean
          default: false
        checkedFinance:
          type: boolean
          default: false
        marshalled:
          type: boolean
          default: false
        haveData:
          type: boolean
          default: false

    EventType:
      type: string
      enum:
        - DEPOSIT
        - WITHDRAW
        - EXCHANGE
        - CORRECTION
        - FEE