openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for Exchange System application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /orders/book:
    get:
      summary: Retrieve all orders
      operationId: getOrderBook
      tags:
        - orders
      responses:
        '200':
          description: A list of all orders in the system
          content:
            application/json:
              schema:
                type: array
                items:
                  type: Order
components:
  schemas:
    CancelOrder:
      type: object
      required:
        - idOrder
        - idCancelOrder
        - pair
        - direction
      properties:
        idOrder:
          type: string
          format: uuid
          description: Unique identifier for the order to be canceled
        idCancelOrder:
          type: string
          format: uuid
          description: Unique identifier for the cancellation order
        pair:
          type: Pair
          description: Trading pair associated with the order
        direction:
          type: Direction
          description: Direction of the order (buy/sell)

    OrderTicket:
      type: object
      required:
        - id
        - amount
        - idUser
        - currency
        - ratio
        - ticketDateUtc
        - pair
        - direction
        - finishOrder
        - flagSaved
        - flagCancelled
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the order ticket
        idUser:
          type: string
          format: uuid
          description: Unique identifier for the user who created the order
        pair:
          type: Pair
          description: Trading pair associated with the order
        direction:
          type: Direction
          description: Direction of the order (buy/sell)
        ticketDateUtc:
          description: Date and time when the order was created, in UTC timezone
          type: string
          format: date-time
        ratio:
          type: integer
          format: int64
          description: Ratio for the order
        amount:
          type: integer
          format: int64
          description: Amount of currency involved in the order
        finishOrder:
          type: boolean
          default: false
          description: Indicates whether the order is finished
        currency:
          type: Currency
          description: Identifier for the currency used in the order
        flagSaved:
          type: boolean
          default: false
          description: Indicates whether the order ticket is saved
        flagCancelled:
          type: boolean
          default: false
          description: Indicates whether the order ticket is canceled

    ExchangeTicket:
      allOf:
        - $ref: "#/components/schemas/OrderTicket"
        - type: object
          properties:
            idOrderReverse:
              type: integer
              format: int64
              description: Unique identifier for the reverse order
            exchangeDateUtc:
              description: Date and time when the exchange occurred, in UTC timezone
              type: string
              format: date-time

    ExchangeEvent:
      type: object
      required:
        - id
        - pair
        - direction
        - ratio
        - idUser
        - journal
        - checkedFinance
        - marshalled
        - haveData
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the exchange event
        action:
          type: string
          description: Description of the action taken during the exchange
        pair:
          type: Pair
          description: Trading pair associated with the exchange event
        value:
          type: number
          description: Value involved in the exchange event
        direction:
          type: Direction
          description: Direction of the exchange event (buy/sell)
        ratio:
          type: number
          description: Ratio for the exchange event
        event:
          type: string
          description: Specific event type or description
        ip:
          type: string
          description: IP address from which the exchange event was initiated
        idUser:
          type: string
          format: uuid
          description: Unique identifier for the user associated with the exchange event
        hash:
          type: integer
          format: int64
          description: Hash value for the exchange event
        journal:
          type: boolean
          default: false
          description: Indicates whether the event is logged in the journal
        checkedFinance:
          type: boolean
          default: false
          description: Indicates whether the financial aspects of the event have been checked
        marshalled:
          type: boolean
          default: false
          description: Indicates whether the event data has been prepared for transmission or storage
        haveData:
          type: boolean
          default: false
          description: Indicates whether the event contains relevant data for processing or analysis

