spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}?reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        default_batch_fetch_size: 100
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.exchange.app.backend.common.serializers.PairSerializer
      value-serializer: org.exchange.app.backend.common.serializers.UserTicketSerializer
      topic: ${SPRING_KAFKA_EXCHANGE_TOPIC}
    consumers:
      consumers-ticket:
        key-deserializer: org.exchange.app.backend.common.deserializers.PairDeserializer
        value-deserializer: org.exchange.app.backend.common.deserializers.UserTicketDeserializer
        group: ${SPRING_KAFKA_TICKET_CONSUMER_GROUP}
        topic: ${SPRING_KAFKA_TICKET_TOPIC}
      consumers-exchange:
        key-deserializer: org.exchange.app.backend.common.deserializers.PairDeserializer
        value-deserializer: org.exchange.app.backend.common.deserializers.UserTicketDeserializer
        group: ${SPRING_KAFKA_EXCHANGE_CONSUMER_GROUP}
        topic: ${SPRING_KAFKA_EXCHANGE_TOPIC}

  json:
    trusted:
      packages: "org.exchange.app.common.api, org.exchange.app.external.api"
    value:
      userTicket:
        type: org.exchange.app.common.api.model.UserTicket
server:
  error:
    include-message: always