spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exchange?reWriteBatchedInserts=true
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        jdbc:
          time_zone: UTC
          batch_size: 100
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
        default_batch_fetch_size: 100
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group: backend-internal
      topic: input-ticket
server:
  error:
    include-message: always