openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for Exchange System application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /tickets/user/{idUser}/create:
    post:
      summary: Send Exchange Ticket
      operationId: saveTicket
      parameters:
        - name: idUser
          in: path
          required: true
          description: The id of the User.
          schema:
            type: integer
            format: int64
      requestBody:
        description: new category object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserTicket'
      tags:
        - tickets
      responses:
        '201':
          description: Ticket saved
        '400':
          description: Error
  /tickets/user/{idUser}:
    get:
      summary: Get all User Tickets
      operationId: getUserTickets
      parameters:
        - name: idUser
          in: path
          required: true
          description: The id of the User.
          schema:
            type: integer
            format: int64
      tags:
        - tickets
      responses:
        '200':
          description: All User Tickets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserTicket'
components:
  schemas:
    UserTicket:
      type: object
      required:
        - order
        - value
        - ratio
        - idUser
        - pair
      properties:
        idUser:
          type: string
          format: uuid
        order:
          type: string
        value:
          type: number
        ratio:
          type: number
        pair:
          type: Pair
        direction:
          type: Direction
