openapi: "3.1.0"
info:
  title: Exchange App
  description: This is a REST API for Exchange System application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /user/ticket:
    post:
      summary: Send Exchange Ticket
      operationId: saveTicket
      requestBody:
        description: new category object
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientTicket'
      tags:
        - user
      responses:
        '201':
          description: Ticket saved
        '400':
          description: Error
components:
  schemas:
    ClientTicket:
      type: object
      properties:
        order:
          type: string