on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Increment Version
        run: |
          if [ "${{ github.base_ref }}" == "main" ]; then
          ./mvnw build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          fi
      - name: Commit changes
        run: |
          if [ "${{ github.event_name }}" == "main" ]; then
            git config --local user.name GitHub Actions
            git config --local user.email "action@github.com"
            git add .
            git commit -m "updated version in pom.xml"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
